### ISSUE TITLE
Github authorization doesn't return a display name. 

### ISSUE THREAD

**Issue by DillonSimeone** [Shiroraven/Jikanri#6]
This is most likely related to issue #5 

See the bottom-left part of the screenshot, the user object returned by a successful sign in is showing no displayname, and verified email is set to false. 

![image](https://user-images.githubusercontent.com/21962421/77243865-2d8df580-6bcc-11ea-9923-c2fb83c19d83.png)

What I expected to see was the same thing as you would get when signing in via google, in the screenshot below.

![image](https://user-images.githubusercontent.com/21962421/77243904-7ba2f900-6bcc-11ea-94b5-ebb132b7f35e.png)

**Comment by DillonSimeone** [comment]
Interesting thing to note: My profile picture is appearing in the returned user object from the github sign-in.

![image](https://user-images.githubusercontent.com/21962421/77243925-b147e200-6bcc-11ea-82b3-6cb8e6dc2ba7.png)

https://avatars2.githubusercontent.com/u/21962421?v=4

**Comment by Shiroraven** [comment]
```octokit = new Octokit({auth: userAccessToken }) octokit.users.getAuthenticated() .then(result => { console.log(result.data.login) // this is the username })```

I don't know why firebase doesn't get it, but supplying Octokit with the Access Token gives you the ability to get their username/login

**Comment by DillonSimeone** [comment]
Oh, shoot! I hoped that it would be straightforward.

It turns out that this function from setup.svelte is getting only the user object. The access token isn't stored in that object! 

`firebase.auth().onAuthStateChanged(function(u) ...`

The signin function below gets the object that have the creds, and the user object.

```
 const signin = provider => {
    firebase
      .auth()
      .signInWithPopup(provider)
      .then(result => {
        // console.log(result.user) // firebase.auth().onAuthStateChanged(function(u) {... Gets the same this. U is user.
        console.log(result)
      }) 
  } 
```

![image](https://user-images.githubusercontent.com/21962421/77287399-b40d0a80-6c92-11ea-9bcf-069e2ad8bbc0.png)

We'll have to get all of the data from the signin function rather than from the observer! BETRAYAL! And to add more fun on top of this... They're not the same for each providers! Top is Github, bottom is google.

![image](https://user-images.githubusercontent.com/21962421/77287827-bcb21080-6c93-11ea-9d39-19c7b5901ab6.png)

So that mean that we'll have to set up spacial parsers for each providers. It's probably going to become blunky enough that we'll have to use... Switches!

```
Switch(result.additionalUserInfo.providerID)
case "github.com": { ... }
case "google.com": { ... }
```

Now how to pass that to the other xxxApiTest.svelte pages (And the other real pages.)? Hmmm. This is localstorage's chance to shine! #3 I'm cheering this on!

**Comment by Shiroraven** [comment]
Svelte has something called Svelte Stores it is a way of sharing data between parts of your App and observing changes.
